[package]
name = "coco"
version = "0.1.0"
authors = ["Phodal Huang <h@phodal.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4" # time format
git2 = "0.13"

# serializing and deserializing
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[workspace]
members = [
  'visual'
]
